<?xml version="1.0" ?>
<testsuite name="DBCheckTestCase-20230812165925" tests="1" time="0.192" failures="0" errors="1">
	<testcase classname="DBCheckTestCase" name="test_db" time="0.192">
		<error type="AttributeError" message="'Connection' object has no attribute 'is_connected'"><![CDATA[Traceback (most recent call last):
  File "C:\Users\wadem\Documents\TastyRepos\tastybackend\stagingtest\test_staging.py", line 53, in test_db
    self.assertTrue(conn.is_connected(), "Database is not running.")
AttributeError: 'Connection' object has no attribute 'is_connected'
]]></error>
	</testcase>
	<system-out><![CDATA[]]></system-out>
	<system-err><![CDATA[]]></system-err>
</testsuite>
